version: '3'

services:
  mongo:
    image: mongo
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017
    container_name: bili-mongo

  redis:
    image: redis
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    container_name: bili-redis

  account:
    image: bossen/bilibili:v20.06.08
    volumes:
      - ./bilibili:/app
    depends_on:
      - mongodb
      - redis
    stdin_open: true
    tty: true
    container_name: bili-account

  bili-user:
    image: bossen/bilibili:v20.06.08
    volumes:
      - ./bilibili:/app
    depends_on:
      - mongodb
      - redis
    command: python run_spider.py user
    container_name: bili-user

  bili-focus:
    image: bossen/weibospider:v20.06.08
    volumes:
      - ./bilibili:/app
    depends_on:
      - mongodb
      - redis
    command: python run_spider.py tweet
    container_name: bili-focus
