version: '3'
services:
  account:
    image: bossen/bilibili:v20.07.01
    volumes:
      - ./bilibili:/app
    external_links:
      - mongo
      - redis
    stdin_open: true
    tty: true
    container_name: bili-account

  bili-kol-user:
    image: bossen/bilibili:v20.10.30
    volumes:
      - ./bilibili:/app
    external_links:
      - mongo
      - redis
    command: python run_spider.py kol_user
    container_name: bili-kol-user

  bili-kol-video:
    image: bossen/bilibili:v20.10.30
    volumes:
      - ./bilibili:/app
    external_links:
      - mongo
      - redis
    command: python run_spider.py kol_video
    container_name: bili-kol-video

networks:
  root_redis-mongo
  external: true