version: '3'

services:
  mongo:
    image: mongo
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 7001:27017
    container_name: bili-mongo

  redis:
    image: redis
    command: redis-server
    ports:
      - 7002:6379
    volumes:
      - ./data/redis:/data
    container_name: bili-redis

  account:
    image: bossen/bilibili:v20.06.24
    volumes:
      - ./bilibili.md:/app
    depends_on:
      - mongo
      - redis
    stdin_open: true
    tty: true
    container_name: bili-account

  bili-user:
    image: bossen/bilibili:v20.06.24
    volumes:
      - ./bilibili.md:/app
    depends_on:
      - mongo
      - redis
    command: python run_spider.py user
    container_name: bili-user

  bili-relation:
    image: bossen/bilibili:v20.06.24
    volumes:
      - ./bilibili.md:/app
    depends_on:
      - mongo
      - redis
    command: python run_spider.py relation
    container_name: bili-relation

  bili-focus:
    image: bossen/bilibili:v20.06.24
    volumes:
      - ./bilibili.md:/app
    depends_on:
      - mongo
      - redis
    command: python run_spider.py focus
    container_name: bili-focus
